<?php

// Check for client photo upload directory root and create it if necessary
function fitcase_init_photo_root_dir() {
	wp_mkdir_p( JLFITCASE__UPLOADS );
}

// Add a custom class to all meta boxes generated by plugin
function add_meta_box_class( $classes ) {
	array_push( $classes, 'jl-fitcase-meta');
	return $classes;
}

// Changes Upload Location for Client photos
function fitcase_client_photo_dir( $args ) {

//	error_log( '$_REQUEST' . PHP_EOL );
//	error_log( print_r( $_REQUEST, true ) );

	if ( isset( $_REQUEST['post_ID'] ) ) {
		$id = $_REQUEST['post_ID'];
		$parent_id = get_post( $id )->post_parent;

		if ( "case_study" == get_post_type( $id ) || "case_study" == get_post_type( $parent_id ) ) {
			$args['path'] = JLFITCASE__UPLOADSDIR;
			$args['url'] = JLFITCASE__UPLOADSURL;
			$args['basedir'] = JLFITCASE__UPLOADSDIR;
			$args['baseurl'] = JLFITCASE__UPLOADSURL;
		}
	}

	return $args;
}
add_filter( 'upload_dir', 'fitcase_client_photo_dir' );

// Disables the Image Sizes for Uploading Images to prevent multiple versions
function fitcase_remove_image_sizes( $sizes, $metadata ) {
	return [];
}

// Creates an array of all admin options that contain the string stored as JLFITCASE__NAMESPACE
function get_fitcase_options() {
	$all_options = wp_load_alloptions();
	$fitcase_options = array();

	foreach ( $all_options as $name => $value ) {
		if ( stristr( $name, JLFITCASE__NAMESPACE ) ) {
			$fitcase_options[ $name ] = $value;
		}
	}

	error_log( print_r( $fitcase_options, true ) );
}